gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    token_parameter_name: refresh_token
    ttl: 2592000 # 30 jours en secondes
    ttl_update: true
    firewall: login
    user_provider: app_user_provider
    user_identity_field: email